Repository dnd-side-project/dnd-7th-7-frontend, pull requests merged in 2022-08, with the labels that each got.

#25 Home 스크린 경로 시작 버튼
  components/Button/Button.jsx
  components/Button/Button.style.js
  components/Button/index.js
  components/Tag/Tag.style.js
  containers/home/RecommendedRoutes/RecommendedRoutes.jsx
  containers/home/RecommendedRoutes/RecommendedRoutes.style.js
  containers/home/RecommendedRoutes/index.js
  containers/home/RecommendedRoutesNearBy/RecommendedRoutesNearBy.jsx
  containers/home/RecommendedRoutesNearBy/RecommendedRoutesNearBy.style.js
  containers/home/RecommendedRoutesNearBy/index.js
  containers/home/TrendingTags/TrendingTags.jsx
  containers/home/TrendingTags/TrendingTags.style.js
  containers/home/TrendingTags/index.js
  screens/Home/Home.jsx
  screens/Home/Home.style.js
Labels: 🔧 Type: Feature, 🟠 Priority: Medium

#29 절대 경로 세팅
  .eslintrc.js
  App.jsx
  babel.config.js
  containers/home/RecommendedRoutes/RecommendedRoutes.jsx
  containers/home/TrendingTags/TrendingTags.jsx
  package.json
  screens/Home/Home.jsx
  screens/MyPage/MyPage.jsx
  yarn.lock
Labels: 🧩 Type: Refactor, 🟢 Priority: Low

#62 마이페이지 스택 네비게이터 세팅
  metro.config.js
  screens/MyPage/CheckPassword/CheckPassword.jsx
  screens/MyPage/CheckPassword/CheckPassword.style.js
  screens/MyPage/CheckPassword/index.js
  screens/MyPage/MyPage.jsx
  screens/MyPage/MypageMain/Mypage.jsx
  screens/MyPage/MypageMain/Mypage.style.js
  screens/MyPage/MypageMain/index.js
Labels: 🟠 Priority: Medium

#65 비밀번호 확인 페이지 / 회원정보 수정 페이지 퍼블리싱
  App.jsx
  package.json
  screens/MyPage/CheckPassword/CheckPassword.jsx
  screens/MyPage/CheckPassword/CheckPassword.style.js
  screens/MyPage/Modify/Modify.jsx
  screens/MyPage/Modify/Modify.style.js
  screens/MyPage/Modify/index.js
  screens/MyPage/MyPage.jsx
  screens/MyPage/MypageMain/Mypage.jsx
  yarn.lock
Labels: 🟠 Priority: Medium

#76 경로 검색 페이지 제작
  assets/images/Group197.png
  assets/images/IC.svg
  assets/images/ICON_Km_20.svg
  assets/images/IC_Loca_24.svg
  assets/images/IC_Smile_28.png
  assets/images/Maskgroup.png
  assets/images/Vector113.png
  assets/images/angle-right.png
  assets/images/graydot.svg
  assets/images/map.png
  assets/images/mountain.png
  assets/images/runMap1.png
  assets/images/runMap2.png
  assets/images/runMap3.png
  assets/images/time.svg
  components/Header/Header.jsx
  screens/BookMark/BookMark.jsx
  screens/BookMark/BookMarkMain/BookMarkMain.jsx
  screens/BookMark/BookMarkMain/BookMarkMain.style.js
  screens/BottomTabs/BottomTabs.jsx
  screens/MyPage/MypageMain/Mypage.jsx
  screens/Search/Search.jsx
  screens/Search/SearchMain/Search.style.js
  screens/Search/SearchMain/SearchMain.jsx
  screens/Search/SearchMain/index.js
Labels: 🟠 Priority: Medium
